### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by parjanya** [harupiyo/time-calculator#1]
This package seems most useful. Is there any chance the documentation to be in English also? Asks a Brazilian who would prefer to write in his native tongue too...

**Comment by harupiyo** [comment]
Hi!
Thank you for your interest.😊

I can create an English version of the document.
(I am not good at English, but I can create it for you using DeepL translation.)

Please note that this little program is personal and has only a limited purpose.😥
I will guide you first so that you will not be disappointed.

Also, I myself still do not fully understand how to use ASDF.
I will be working to make sure that it is ready for use, so I hope you will wait a while.

**Comment by parjanya** [comment]
This should be a standard library for Common Lisp.

I can help with the translation :)

**Comment by harupiyo** [comment]
Hi @parjanya !

Now that we have confirmed that it works, we have created an English version of the document.

https://github.com/harupiyo/time-calculator/blob/main/README.md

Could you please read it?

**Comment by parjanya** [comment]
Thanks, @harupiyo! Now it is very clear what the code does, I hope to take a closer look and perhaps add some things to it :)
